import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/*
  IMPORTANT:
  We are using RELATIVE imports to avoid alias issues.
*/
import Navbar from "../components/ui/Navbar";
import Sidebar from "../components/ui/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col h-screen">
          {/* Navbar */}
          <Navbar />

          {/* Sidebar + Content */}
          <div className="flex flex-1">
            <Sidebar />

            <main className="flex-1 p-6 overflow-y-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
